# Generated by Django 2.2.8 on 2020-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
