# Generated by Django 3.1.3 on 2020-11-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_teacher_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='GroupOfStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('subjects', models.ManyToManyField(to='core.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='groupOfStudents',
            field=models.ManyToManyField(to='core.GroupOfStudents'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupofstudents'),
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
