# Generated by Django 3.1.3 on 2020-11-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201130_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupofstudents',
            options={'verbose_name_plural': 'GroupsOfStudents'},
        ),
    ]
